const NEIGHBORHOODS = [
  {
    id:"downtown", name:"Downtown", center:[32.3779,-86.3097], radius:900, color:"#3182ce",
    description:"Montgomery's beating heart — government, commerce, and civil rights history converge here.",
    business:{total:342,newOpen:47,closed:18,netGrowth:8.5,avgRating:3.9,footTraffic:85,
      topCats:["Restaurants","Legal Services","Retail","Entertainment"],
      insight:"Yelp reviews mention 'revitalization' 3x more than 2023. Foot traffic on Dexter Ave up 22% year-over-year per Google Trends data."},
    safety:{crimeRate:42,crimeChange:-12,perception:68,mediaIndex:78,gap:"Over-reported",trend:"Improving",
      insight:"Crime down 12% YoY but local TV news coverage of downtown incidents up 23%. The perception gap is the widest in the city."},
    spaces:{list:[{name:"Riverwalk Park",type:"Park",util:82},{name:"Court Square Fountain",type:"Historic Plaza",util:65},{name:"Union Station Train Shed",type:"Venue",util:58},{name:"Riverfront Trail",type:"Trail - 2.5mi",util:71}]},
    development:{permits:28,avgDays:34,projects:["Riverfront Mixed-Use Development — $4.2M","Commerce St Streetscape — $1.8M","Historic Kress Building Renovation"]},
    civic:{open311:23,avgResDays:4.2,topIssues:["Street Lighting","Sidewalk Repair","Parking Meters"],grade:"B+"},
    history:{title:"Where a Nation Changed Course",text:"Nearly every block downtown holds a piece of American history. Dexter Avenue connects the Alabama State Capitol — where Jefferson Davis took the oath as Confederate president — to the church where Dr. King organized the Montgomery Bus Boycott.",
      landmarks:[{icon:"&#9851;",name:"Dexter Ave King Memorial Baptist Church",desc:"Where Dr. King served as pastor and launched the boycott movement"},{icon:"&#9733;",name:"Alabama State Capitol",desc:"Endpoint of the Selma to Montgomery marches"},{icon:"&#10047;",name:"Civil Rights Memorial Center",desc:"Maya Lin-designed memorial honoring 40 martyrs"},{icon:"&#9962;",name:"Rosa Parks Museum",desc:"Interactive museum at the site of her arrest"}]},
    restaurants:[
      {name:"Central",cuisine:"Southern Fine Dining",rating:4.5,price:"$$$",note:"Chef-driven seasonal menus in a beautifully restored space"},
      {name:"Chris' Hot Dogs",cuisine:"American Classic",rating:4.3,price:"$",note:"A Montgomery institution since 1917"},
      {name:"Cahawba House",cuisine:"Southern Comfort",rating:4.2,price:"$$",note:"Farm-to-table with Alabama craft beer"},
      {name:"Sa-Za",cuisine:"Italian",rating:4.4,price:"$$",note:"Wood-fired pizzas and house-made pasta"}
    ],
    parking:[{name:"Commerce St Garage",type:"Garage",spots:450,rate:"$1/hr"},{name:"Tallapoosa St Lot",type:"Surface Lot",spots:120,rate:"$0.75/hr"},{name:"Dexter Ave Metered",type:"Street",spots:85,rate:"$0.50/hr"},{name:"RSA Tower Garage",type:"Garage",spots:300,rate:"$1.25/hr"}],
    narrative:"Downtown is buzzing. Forty-seven new businesses opened this year \u2014 restaurants, legal offices, creative spaces. Crime dropped 12%, though residents say street lighting still needs work. City services respond to 311 requests in about 4 days. The Dexter Avenue corridor, once a symbol of division, is now the heart of Montgomery\u2019s renaissance.",
    voices:[{author:"Sarah J.",role:"Resident since 2018",quote:"I moved here for the history and stayed for the energy. Dexter Ave on a Saturday morning is a completely different city from five years ago."},{author:"Marcus W.",role:"Business owner",quote:"We opened our restaurant here because we believe in downtown. Foot traffic is up, and people are starting to see what we see."},{author:"Rev. Tanya H.",role:"Dexter Ave church member",quote:"This street carries so much history. It\u2019s good to see new life here \u2014 as long as we remember what this ground means."}],
    eras:[{year:"1955",title:"Bus Boycott",connection:"The boycott was organized from Dexter Ave King Memorial Church, just blocks from the Capitol."},{year:"1961",title:"Freedom Riders",connection:"Freedom Riders arrived at the Greyhound station on Court Street, in the heart of downtown."},{year:"1965",title:"Selma to Montgomery",connection:"The 54-mile march ended on the steps of the Alabama State Capitol on Dexter Avenue."},{year:"2018",title:"Memorial Opens",connection:"The National Memorial for Peace and Justice opened just west of downtown, drawing global attention."}],
    wishes:[{id:1,text:"Better street lighting on Dexter Ave after dark",votes:47},{id:2,text:"More affordable housing options downtown",votes:38},{id:3,text:"Weekend farmer\u2019s market at Court Square",votes:31},{id:4,text:"Public art installations celebrating civil rights history",votes:28}],
    communityStories:[{author:"James T.",role:"History teacher",quote:"I bring my students downtown every semester. Walking from the church to the Capitol, you can feel the weight of what happened here. It\u2019s the most powerful classroom in America."}]
  },
  {
    id:"old-cloverdale", name:"Old Cloverdale", center:[32.3520,-86.3130], radius:700, color:"#805ad5",
    description:"Tree-lined streets, historic homes, and a thriving local food scene.",
    business:{total:86,newOpen:12,closed:4,netGrowth:9.3,avgRating:4.3,footTraffic:62,topCats:["Restaurants","Boutiques","Art Galleries","Cafes"],insight:"Highest average Yelp rating in the city. Google reviews frequently mention 'walkable' and 'hidden gem.' Bright Data sentiment score: 91/100."},
    safety:{crimeRate:14,crimeChange:-8,perception:22,mediaIndex:12,gap:"Accurate",trend:"Stable",insight:"One of the safest neighborhoods. Perception closely matches reality."},
    spaces:{list:[{name:"Cloverdale Park",type:"Neighborhood Park",util:78},{name:"Cloverdale Playhouse",type:"Community Theater",util:68}]},
    development:{permits:8,avgDays:28,projects:["Cloverdale Bottom Mixed-Use Infill","Historic Home Restoration Grants"]},
    civic:{open311:7,avgResDays:3.1,topIssues:["Tree Trimming","Storm Drain Clearing"],grade:"A"},
    history:{title:"Literary Montgomery",text:"F. Scott Fitzgerald and Zelda Sayre lived here in the 1930s. The neighborhood retains its early 20th-century charm.",landmarks:[{icon:"&#9998;",name:"Fitzgerald Museum",desc:"The only museum dedicated to F. Scott and Zelda Fitzgerald"},{icon:"&#127917;",name:"Cloverdale Playhouse",desc:"Community theater since 1958"}]},
    restaurants:[{name:"Vintage Year",cuisine:"Upscale American",rating:4.6,price:"$$$",note:"Montgomery's top-rated fine dining"},{name:"El Rey Burrito Lounge",cuisine:"Mexican Fusion",rating:4.4,price:"$",note:"Beloved local spot"},{name:"Leroy",cuisine:"Craft Cocktails",rating:4.3,price:"$$",note:"Date night favorite"}],
    parking:[{name:"Cloverdale Bottom Lot",type:"Surface Lot",spots:40,rate:"Free"},{name:"Fairview Ave Street",type:"Street",spots:60,rate:"Free"}],
    narrative:"Old Cloverdale is Montgomery\u2019s walkable gem. Twelve new businesses opened this year \u2014 mostly boutiques and cafes \u2014 pushing growth to nearly 10%. With the city\u2019s highest Yelp ratings and one of its lowest crime rates, this neighborhood proves that character and safety can coexist. The Fitzgerald Museum keeps its literary legacy alive.",
    voices:[{author:"Diana K.",role:"20-year resident",quote:"Cloverdale hasn\u2019t lost its soul. The old homes, the trees, the Playhouse \u2014 it still feels like a neighborhood, not a development."},{author:"Chef Miguel R.",role:"Restaurant owner",quote:"People drive across town to eat here. The walkability and the vibe \u2014 that\u2019s what makes our restaurants work."}],
    eras:[{year:"1930s",title:"Literary Heritage",connection:"F. Scott and Zelda Fitzgerald lived here, writing some of America\u2019s most celebrated fiction in these tree-lined streets."}],
    wishes:[{id:1,text:"Protect historic homes from demolition for new builds",votes:52},{id:2,text:"More sidewalk repairs for walkability",votes:34},{id:3,text:"Community garden on the Cloverdale Bottom lot",votes:27}],
    communityStories:[{author:"Emma L.",role:"Cloverdale Playhouse volunteer",quote:"The Playhouse is the heartbeat of this neighborhood. Every show brings people together \u2014 from teenagers to grandparents \u2014 and reminds us why small communities matter."}]
  },
  {
    id:"midtown", name:"Midtown", center:[32.3650,-86.3050], radius:750, color:"#d69e2e",
    description:"Montgomery's cultural center — museums, galleries, and a growing creative economy.",
    business:{total:158,newOpen:22,closed:12,netGrowth:6.3,avgRating:4.0,footTraffic:55,topCats:["Arts & Culture","Healthcare","Professional Services","Dining"],insight:"Creative economy growing. Bright Data shows 34% increase in event-related check-ins year-over-year."},
    safety:{crimeRate:28,crimeChange:-6,perception:38,mediaIndex:30,gap:"Slight over-report",trend:"Improving",insight:"Moderate crime rate trending downward. Perception slightly elevated due to proximity to higher-crime areas in media coverage."},
    spaces:{list:[{name:"Montgomery Museum of Fine Arts",type:"Museum",util:72},{name:"Blount Cultural Park",type:"Park - 250 acres",util:68},{name:"Shakespeare Garden",type:"Garden",util:45}]},
    development:{permits:15,avgDays:31,projects:["Midtown Arts District Streetscape","New mixed-use on Norman Bridge"]},
    civic:{open311:15,avgResDays:3.8,topIssues:["Pothole Repair","Street Signage"],grade:"B+"},
    history:{title:"The Cultural Heart",text:"Home to the Montgomery Museum of Fine Arts, Blount Cultural Park, and a growing arts district attracting young creatives.",landmarks:[{icon:"&#127912;",name:"Montgomery Museum of Fine Arts",desc:"Free admission. American art and rotating exhibitions"},{icon:"&#127795;",name:"Blount Cultural Park",desc:"250 acres of green space and the Alabama Shakespeare Festival"}]},
    restaurants:[{name:"Dreamland Bar-B-Que",cuisine:"BBQ",rating:4.1,price:"$",note:"Legendary Alabama BBQ"},{name:"Tomatino's Midtown",cuisine:"Pizza",rating:4.0,price:"$",note:"Solid casual lunch spot"}],
    parking:[{name:"Museum Parking",type:"Surface Lot",spots:200,rate:"Free"},{name:"Woodmere Blvd Street",type:"Street",spots:40,rate:"Free"}],
    narrative:"Midtown is where Montgomery\u2019s creative energy lives. Home to the Museum of Fine Arts and the Alabama Shakespeare Festival, this neighborhood sees growing cultural investment. Twenty-two new businesses opened this year, many in the arts. Crime is moderate but trending down, and the city responds quickly to 311 requests.",
    voices:[{author:"Alicia M.",role:"Artist & gallery owner",quote:"The arts district is real. It\u2019s not just marketing \u2014 there are actual studios, actual artists, actual foot traffic now."},{author:"Dr. Howard P.",role:"Museum volunteer",quote:"Free admission at the museum means everyone can participate in culture. That\u2019s rare and worth protecting."}],
    eras:[{year:"1960s\u201380s",title:"Cultural Investment",connection:"Post-civil rights Montgomery invested in cultural institutions, leading to the Museum of Fine Arts and Blount Cultural Park."}],
    wishes:[{id:1,text:"Extended museum hours on weekends",votes:41},{id:2,text:"Better public transit connecting Midtown to Downtown",votes:35},{id:3,text:"More public murals and street art",votes:30}],
    communityStories:[{author:"Kwame S.",role:"Local musician",quote:"I play at venues here every week. The audience is growing \u2014 younger, more diverse. Midtown feels like it\u2019s on the edge of something big."}]
  },
  {
    id:"capitol-heights", name:"Capitol Heights", center:[32.3700,-86.2880], radius:650, color:"#dd6b20",
    description:"An emerging neighborhood east of downtown with deep roots and growing investment.",
    business:{total:64,newOpen:15,closed:8,netGrowth:10.9,avgRating:3.6,footTraffic:35,topCats:["Auto Services","Food & Beverage","Retail","Churches"],insight:"Highest net business growth rate in the city. Bright Data shows new Google Business listings up 28% this year."},
    safety:{crimeRate:52,crimeChange:-5,perception:74,mediaIndex:65,gap:"Over-reported",trend:"Improving",insight:"Crime declining but still above city average. Media coverage 1.4x per incident vs. citywide average."},
    spaces:{list:[{name:"Oak Park",type:"Neighborhood Park",util:42},{name:"Capitol Heights Community Center",type:"Community Center",util:55}]},
    development:{permits:18,avgDays:29,projects:["Capitol Heights Revitalization Phase II","New affordable housing on Holt St","Streetlight modernization"]},
    civic:{open311:32,avgResDays:5.1,topIssues:["Vacant Property Complaints","Street Lighting","Illegal Dumping"],grade:"B-"},
    history:{title:"The Heart of the Boycott",text:"Capitol Heights is where the Montgomery Bus Boycott lived. Holt Street Baptist Church, where thousands gathered for the first mass meeting, is here.",landmarks:[{icon:"&#9851;",name:"Holt Street Baptist Church",desc:"Site of the first mass meeting — Dec 5, 1955"},{icon:"&#127960;",name:"Holt Street Fountain",desc:"Memorial marker at the historic site"}]},
    restaurants:[{name:"Martin's Restaurant",cuisine:"Southern Soul Food",rating:4.2,price:"$",note:"Best fried catfish — cash only"},{name:"Capitol Heights Diner",cuisine:"Breakfast & Lunch",rating:3.9,price:"$",note:"No-frills, big portions"}],
    parking:[{name:"Street parking",type:"Street",spots:100,rate:"Free"}],
    narrative:"Capitol Heights is where Montgomery\u2019s civil rights story lives and breathes. Holt Street Baptist Church, site of the first mass meeting of the Bus Boycott, anchors this community. It has the city\u2019s highest business growth rate \u2014 10.9% \u2014 but also faces challenges: crime is elevated, and 311 response times lag behind other neighborhoods.",
    voices:[{author:"Deacon Willie B.",role:"Holt St. church elder",quote:"People drive past this neighborhood without knowing what happened here. December 5, 1955 \u2014 thousands gathered right here and changed America."},{author:"Keisha N.",role:"Small business owner",quote:"I opened my shop because this neighborhood deserves investment from people who actually live here, not outsiders."}],
    eras:[{year:"1955",title:"First Mass Meeting",connection:"On December 5, 1955, thousands packed Holt Street Baptist Church and voted to continue the boycott \u2014 the movement\u2019s founding moment."},{year:"1960s",title:"Community Organizing",connection:"Capitol Heights remained a center of Black civic organizing throughout the civil rights era."}],
    wishes:[{id:1,text:"Historical markers at all significant civil rights sites",votes:56},{id:2,text:"Faster 311 response times \u2014 we deserve equal service",votes:44},{id:3,text:"Youth job training programs in the neighborhood",votes:39},{id:4,text:"Better lighting and sidewalks on Holt Street",votes:33}],
    communityStories:[{author:"Dorothy M.",role:"Retired teacher, lifelong resident",quote:"My grandmother walked to work during the boycott. She walked for 381 days. That\u2019s the spirit of Capitol Heights \u2014 we don\u2019t give up."}]
  },
  {
    id:"garden-district", name:"Garden District", center:[32.3570,-86.3250], radius:650, color:"#38a169",
    description:"A leafy residential area with parks, local shops, and a strong sense of community.",
    business:{total:52,newOpen:8,closed:3,netGrowth:9.6,avgRating:4.1,footTraffic:38,topCats:["Lawn & Garden","Home Services","Cafes","Pet Services"],insight:"Bright Data shows neighborhood mentions in real estate listings up 45%."},
    safety:{crimeRate:18,crimeChange:-10,perception:25,mediaIndex:10,gap:"Accurate",trend:"Improving",insight:"Low crime area with accurate public perception."},
    spaces:{list:[{name:"Gateway Park",type:"Park",util:70},{name:"Garden District Walking Trail",type:"Trail - 1.2mi",util:65},{name:"Fairview Community Garden",type:"Garden",util:50}]},
    development:{permits:6,avgDays:25,projects:["Pocket park expansion","Sidewalk connectivity improvements"]},
    civic:{open311:9,avgResDays:2.8,topIssues:["Tree Debris","Stormwater","Animal Control"],grade:"A"},
    history:{title:"The Garden Suburb",text:"Developed in the 1920s-1940s as one of Montgomery's first planned residential areas, designed around green space and walkability.",landmarks:[{icon:"&#127793;",name:"Community Victory Garden",desc:"Revival of WWII-era community gardening"},{icon:"&#127968;",name:"Garden District Historic Homes",desc:"Well-preserved 1930s bungalows"}]},
    restaurants:[{name:"The Greenhouse",cuisine:"Coffee & Pastries",rating:4.4,price:"$",note:"Neighborhood coffee shop with a devoted following"}],
    parking:[{name:"Street parking",type:"Street",spots:80,rate:"Free"}],
    narrative:"The Garden District lives up to its name \u2014 green, quiet, and close-knit. With the city\u2019s fastest 311 response time (2.8 days) and low crime, this planned 1920s neighborhood shows what intentional design creates. Eight new businesses opened this year, many home-based. Real estate listings mentioning the neighborhood are up 45%.",
    voices:[{author:"Patricia G.",role:"30-year resident",quote:"We moved here for the sidewalks and the trees. Thirty years later, it\u2019s still the most walkable part of Montgomery."},{author:"Tom & Linda H.",role:"Retired couple",quote:"The community garden brought us together with neighbors we\u2019d never met. Now we share more than tomatoes."}],
    eras:[{year:"1920s\u201340s",title:"Planned Community",connection:"One of Montgomery\u2019s first planned residential areas, designed around green space and pedestrian access."}],
    wishes:[{id:1,text:"Expand the community garden to more blocks",votes:29},{id:2,text:"Traffic calming on Fairview Ave",votes:22},{id:3,text:"Dog park in Gateway Park",votes:18}],
    communityStories:[{author:"Young J.",role:"New homeowner",quote:"We chose the Garden District over the suburbs. It\u2019s quiet, walkable, and our kids can ride their bikes safely. That\u2019s priceless."}]
  },
  {
    id:"dalraida", name:"Dalraida", center:[32.4050,-86.2700], radius:800, color:"#e53e3e",
    description:"A large suburban neighborhood — diverse, family-oriented, and commercially active.",
    business:{total:210,newOpen:18,closed:14,netGrowth:1.9,avgRating:3.7,footTraffic:60,topCats:["Retail","Healthcare","Fast Food","Auto Services"],insight:"Bright Data shows high search volume for 'Dalraida restaurants' — demand may outstrip options."},
    safety:{crimeRate:38,crimeChange:-3,perception:45,mediaIndex:35,gap:"Slight over-report",trend:"Stable",insight:"Mid-range crime rate. Property crime is the main driver."},
    spaces:{list:[{name:"Lagoon Park",type:"Park & Golf Course",util:75},{name:"Dalraida Community Center",type:"Community Center",util:60},{name:"Lagoon Park Trail",type:"Trail - 1.8mi",util:55}]},
    development:{permits:12,avgDays:32,projects:["Wares Ferry Road widening","New retail pad site on Eastern Blvd"]},
    civic:{open311:28,avgResDays:4.5,topIssues:["Road Maintenance","Traffic Signals","Drainage"],grade:"B"},
    history:{title:"Suburban Expansion",text:"Dalraida grew rapidly in the 1960s-1980s. Named after a Scottish-Irish kingdom, it became one of the city's most diverse areas.",landmarks:[{icon:"&#9971;",name:"Lagoon Park Golf Course",desc:"Public 18-hole course"},{icon:"&#127963;",name:"Eastern Blvd Corridor",desc:"Main commercial strip"}]},
    restaurants:[{name:"Capitol Oyster Bar",cuisine:"Seafood",rating:4.3,price:"$$",note:"Fresh Gulf oysters — a Montgomery favorite"},{name:"Taste of Bangkok",cuisine:"Thai",rating:4.1,price:"$$",note:"Authentic Thai with generous portions"}],
    parking:[{name:"Business lot parking",type:"Surface Lots",spots:300,rate:"Free"}],
    narrative:"Dalraida is Montgomery\u2019s most diverse large neighborhood \u2014 family-oriented, commercially active, and affordable. Growth is slow but steady at 1.9%. The area has strong community anchors like Lagoon Park and a busy commercial corridor on Eastern Blvd. Residents say they want more restaurant options and better road maintenance.",
    voices:[{author:"Fatima A.",role:"Immigrant business owner",quote:"My family came here from Somalia. Dalraida accepted us. Our restaurant serves Somali food and soul food \u2014 that\u2019s Dalraida in one sentence."},{author:"Coach Ray D.",role:"Youth league organizer",quote:"Lagoon Park is where this community comes together. Saturdays during football season, you\u2019ll see every part of Dalraida on those fields."}],
    eras:[{year:"1960s\u201380s",title:"Suburban Growth",connection:"Dalraida grew as Montgomery expanded eastward. It became one of the city\u2019s first truly diverse suburban neighborhoods."}],
    wishes:[{id:1,text:"More diverse restaurant options on Eastern Blvd",votes:38},{id:2,text:"Road resurfacing on Wares Ferry Road",votes:31},{id:3,text:"After-school programs at the community center",votes:27},{id:4,text:"Better crosswalks on Eastern Blvd",votes:21}],
    communityStories:[{author:"Maria C.",role:"Parent & PTA member",quote:"Dalraida schools are more diverse than anywhere in Montgomery. My kids\u2019 best friends come from five different countries. That\u2019s the real strength of this neighborhood."}]
  },
  {
    id:"eastdale", name:"Eastdale", center:[32.3780,-86.2550], radius:700, color:"#4fd1c5",
    description:"East Montgomery's growing commercial hub with new development.",
    business:{total:175,newOpen:25,closed:10,netGrowth:8.6,avgRating:3.8,footTraffic:68,topCats:["Retail","Restaurants","Healthcare","Fitness"],insight:"Eastdale Mall area reinventing itself. Bright Data shows Google searches up 40%."},
    safety:{crimeRate:32,crimeChange:-9,perception:48,mediaIndex:42,gap:"Over-reported",trend:"Improving",insight:"Crime down 9% but media narrative hasn't caught up. Scraped Reddit threads still reference outdated perceptions."},
    spaces:{list:[{name:"Eastdale Park",type:"Park",util:48},{name:"Vaughn Road Trail",type:"Trail - 2.0mi",util:52}]},
    development:{permits:22,avgDays:30,projects:["Eastdale Town Center Redevelopment","New medical office complex","Taylor Road corridor improvements"]},
    civic:{open311:19,avgResDays:4.0,topIssues:["Road Resurfacing","Traffic Flow","Commercial Signage"],grade:"B"},
    history:{title:"East Side Rising",text:"Eastdale emerged as a commercial center in the 1970s-1980s. The area is now experiencing a second wave of investment.",landmarks:[{icon:"&#127963;",name:"Eastdale Town Center",desc:"Former mall becoming mixed-use destination"},{icon:"&#128137;",name:"Baptist Health Campus",desc:"Major medical complex"}]},
    restaurants:[{name:"Filet & Vine",cuisine:"Steakhouse",rating:4.2,price:"$$$",note:"Upscale dining — a sign of the area's rise"},{name:"Maki Fresh",cuisine:"Sushi & Poke",rating:4.0,price:"$$",note:"Fast-casual sushi that's actually good"}],
    parking:[{name:"Town Center lots",type:"Surface Lots",spots:500,rate:"Free"}],
    narrative:"Eastdale is reinventing itself. Twenty-five new businesses opened this year, and the old Eastdale Mall area is transforming into a mixed-use center. Crime is down 9% but outdated perceptions linger \u2014 Reddit threads still reference old data. With $4M+ in development projects, this is a neighborhood betting on its future.",
    voices:[{author:"Brandon T.",role:"Developer",quote:"We\u2019re building something new here. The old mall narrative is dead \u2014 Eastdale Town Center is going to be a real destination."},{author:"Nurse Pam S.",role:"Baptist Health employee",quote:"I work at the medical campus and I live nearby. The commute, the restaurants, the parks \u2014 it\u2019s getting better every year."}],
    eras:[{year:"1970s\u201380s",title:"Commercial Boom",connection:"Eastdale emerged as a commercial center during Montgomery\u2019s eastward expansion, anchored by the Eastdale Mall."},{year:"2020s",title:"Reinvention",connection:"The old mall is being reimagined as mixed-use space \u2014 part of a national trend of suburban renewal."}],
    wishes:[{id:1,text:"Better walking/biking paths connecting to downtown",votes:35},{id:2,text:"More green space in the town center redevelopment",votes:29},{id:3,text:"Outdoor dining areas at new restaurants",votes:23}],
    communityStories:[{author:"Aisha R.",role:"High school student",quote:"Everyone says Eastdale is boring. It\u2019s not. The trail is great, the new sushi place is good, and things are actually changing. Give it time."}]
  },
  {
    id:"woodley-park", name:"Woodley Park", center:[32.3920,-86.2850], radius:600, color:"#667eea",
    description:"An established residential neighborhood with good schools and quiet streets.",
    business:{total:38,newOpen:5,closed:2,netGrowth:7.9,avgRating:4.2,footTraffic:25,topCats:["Home Services","Tutoring","Lawn Care","Childcare"],insight:"Bright Data school rating data shows above-average elementary school scores — a driver of home values."},
    safety:{crimeRate:12,crimeChange:-15,perception:15,mediaIndex:5,gap:"Accurate",trend:"Improving",insight:"One of the safest areas. Very low media coverage. Perception and reality aligned."},
    spaces:{list:[{name:"Woodley Park",type:"Neighborhood Park",util:70},{name:"Woodley Walking Path",type:"Trail - 0.8mi",util:62}]},
    development:{permits:4,avgDays:22,projects:["Residential lot development","Sidewalk ADA improvements"]},
    civic:{open311:5,avgResDays:2.5,topIssues:["Yard Waste Collection","Speed Humps"],grade:"A+"},
    history:{title:"The Quiet Backbone",text:"Woodley Park represents the suburban dream of Montgomery's north side. Neighborhoods like this are the stable backbone of any city.",landmarks:[{icon:"&#127968;",name:"Woodley Park Neighborhood",desc:"Well-maintained 1970s-80s homes"},{icon:"&#127891;",name:"Top-Rated Elementary Schools",desc:"Above-average school ratings"}]},
    restaurants:[{name:"Neighborhood Deli & Grill",cuisine:"American",rating:4.0,price:"$",note:"The kind of place where everyone knows your name"}],
    parking:[{name:"Street parking",type:"Street",spots:50,rate:"Free"}],
    narrative:"Woodley Park is Montgomery\u2019s quiet achiever. The safest neighborhood in the data, with the fastest 311 response (2.5 days) and the highest civic grade (A+). Growth is steady at 7.9%. School ratings are above average. It\u2019s not flashy, but for families, it\u2019s exactly what a neighborhood should be.",
    voices:[{author:"Jennifer & David W.",role:"Parents of three",quote:"The schools are great, the neighborhood is safe, and our kids play outside until dark. We don\u2019t need trendy \u2014 we need stable."},{author:"Mr. Harold T.",role:"Retired postal worker",quote:"I\u2019ve lived here since 1982. It\u2019s never made the news. That\u2019s the best compliment a neighborhood can get."}],
    eras:[{year:"1970s\u201380s",title:"Suburban Stability",connection:"Built during Montgomery\u2019s suburban expansion, Woodley Park represented the promise of stable, middle-class neighborhood life."}],
    wishes:[{id:1,text:"Playground equipment upgrades at Woodley Park",votes:24},{id:2,text:"Speed humps on cut-through streets",votes:19},{id:3,text:"Neighborhood watch program expansion",votes:15}],
    communityStories:[{author:"Lisa P.",role:"Neighborhood association president",quote:"We have a block party every Fourth of July. Last year, 200 people showed up. That doesn\u2019t happen in neighborhoods that don\u2019t care about each other."}]
  }
];

const POI_DATA = {
  landmarks: [
    {name:"Dexter Ave King Memorial Baptist Church",coords:[32.3773,-86.3065],desc:"Where Dr. King organized the Montgomery Bus Boycott. National Historic Landmark."},
    {name:"Alabama State Capitol",coords:[32.3770,-86.3003],desc:"Endpoint of the Selma-to-Montgomery marches."},
    {name:"Rosa Parks Museum",coords:[32.3810,-86.3120],desc:"Interactive museum at the site where Rosa Parks was arrested in 1955."},
    {name:"Civil Rights Memorial Center",coords:[32.3762,-86.3085],desc:"Maya Lin-designed memorial honoring 40 martyrs."},
    {name:"National Memorial for Peace and Justice",coords:[32.3722,-86.3145],desc:"The nation's first memorial dedicated to victims of lynching."},
    {name:"Legacy Museum",coords:[32.3795,-86.3100],desc:"From Enslavement to Mass Incarceration."},
    {name:"Freedom Rides Museum",coords:[32.3818,-86.3105],desc:"The restored Greyhound station where Freedom Riders arrived in 1961."},
    {name:"Holt Street Baptist Church",coords:[32.3690,-86.2895],desc:"Site of the first mass meeting of the Montgomery Bus Boycott."},
    {name:"First White House of the Confederacy",coords:[32.3778,-86.3030],desc:"Historic house where Jefferson Davis lived."},
    {name:"F. Scott Fitzgerald Museum",coords:[32.3530,-86.3120],desc:"The only museum dedicated to F. Scott and Zelda Fitzgerald."},
    {name:"Montgomery Performing Arts Centre",coords:[32.3805,-86.3075],desc:"Premier performing arts venue."},
    {name:"Alabama Shakespeare Festival",coords:[32.3590,-86.2960],desc:"One of the world's largest Shakespeare festivals."}
  ],
  parks: [
    {name:"Riverwalk Park",coords:[32.3830,-86.3130],desc:"Scenic park along the Alabama River.",acres:20},
    {name:"Blount Cultural Park",coords:[32.3595,-86.2955],desc:"250-acre park with Museum and Shakespeare Festival.",acres:250},
    {name:"Cloverdale Park",coords:[32.3510,-86.3140],desc:"Charming neighborhood park.",acres:5},
    {name:"Lagoon Park",coords:[32.4060,-86.2680],desc:"Large park with golf course and fishing lagoon.",acres:200},
    {name:"Gateway Park",coords:[32.3575,-86.3240],desc:"Community park with playground.",acres:8},
    {name:"Oak Park",coords:[32.3710,-86.2870],desc:"Neighborhood green space with basketball courts.",acres:6},
    {name:"Eastdale Park",coords:[32.3795,-86.2535],desc:"Growing park with sports fields.",acres:15},
    {name:"Woodley Park",coords:[32.3925,-86.2840],desc:"Quiet neighborhood park.",acres:4},
    {name:"Court Square Fountain",coords:[32.3775,-86.3095],desc:"Historic 1885 fountain downtown.",acres:1},
    {name:"Union Station Train Shed",coords:[32.3825,-86.3095],desc:"Restored 1898 train shed.",acres:2}
  ],
  trails: [
    {name:"Riverwalk Trail",coords:[32.3840,-86.3150],desc:"Paved trail along the Alabama River.",miles:2.5,surface:"Paved"},
    {name:"Blount Cultural Park Trail",coords:[32.3580,-86.2980],desc:"Nature trail through woods and meadows.",miles:3.2,surface:"Natural"},
    {name:"Lagoon Park Trail",coords:[32.4050,-86.2695],desc:"Loop trail around the lagoon.",miles:1.8,surface:"Paved"},
    {name:"Garden District Walking Trail",coords:[32.3560,-86.3260],desc:"Neighborhood walking loop.",miles:1.2,surface:"Sidewalk"},
    {name:"Vaughn Road Trail",coords:[32.3770,-86.2560],desc:"Multi-use path connecting east neighborhoods.",miles:2.0,surface:"Paved"},
    {name:"Woodley Walking Path",coords:[32.3910,-86.2855],desc:"Short neighborhood walking path.",miles:0.8,surface:"Paved"}
  ],
  parking: [
    {name:"Commerce St Garage",coords:[32.3785,-86.3110],desc:"Multi-level garage near Dexter Ave.",spots:450,rate:"$1/hr"},
    {name:"RSA Tower Garage",coords:[32.3765,-86.3120],desc:"Covered parking near government buildings.",spots:300,rate:"$1.25/hr"},
    {name:"Tallapoosa St Lot",coords:[32.3790,-86.3080],desc:"Open surface lot near Court Square.",spots:120,rate:"$0.75/hr"},
    {name:"Dexter Ave Metered",coords:[32.3775,-86.3050],desc:"Street metered parking.",spots:85,rate:"$0.50/hr"},
    {name:"Riverwalk Parking",coords:[32.3835,-86.3125],desc:"Free lot at the Riverwalk.",spots:60,rate:"Free"},
    {name:"Cloverdale Bottom Lot",coords:[32.3515,-86.3125],desc:"Free lot for Cloverdale shops.",spots:40,rate:"Free"},
    {name:"Museum Parking",coords:[32.3600,-86.2965],desc:"Free lot at Fine Arts Museum.",spots:200,rate:"Free"},
    {name:"Eastdale Town Center",coords:[32.3785,-86.2545],desc:"Large free shopping center lot.",spots:500,rate:"Free"}
  ],
  restaurants: [
    {name:"Central",coords:[32.3782,-86.3100],cuisine:"Southern Fine Dining",rating:4.5,price:"$$$"},
    {name:"Chris' Hot Dogs",coords:[32.3778,-86.3080],cuisine:"American Classic (since 1917)",rating:4.3,price:"$"},
    {name:"Cahawba House",coords:[32.3792,-86.3085],cuisine:"Southern Comfort",rating:4.2,price:"$$"},
    {name:"Sa-Za",coords:[32.3788,-86.3090],cuisine:"Italian",rating:4.4,price:"$$"},
    {name:"Vintage Year",coords:[32.3525,-86.3135],cuisine:"Upscale American",rating:4.6,price:"$$$"},
    {name:"El Rey Burrito Lounge",coords:[32.3518,-86.3128],cuisine:"Mexican Fusion",rating:4.4,price:"$"},
    {name:"Leroy",coords:[32.3512,-86.3122],cuisine:"Craft Cocktails",rating:4.3,price:"$$"},
    {name:"Capitol Oyster Bar",coords:[32.4045,-86.2710],cuisine:"Seafood",rating:4.3,price:"$$"},
    {name:"Dreamland Bar-B-Que",coords:[32.3645,-86.3060],cuisine:"BBQ",rating:4.1,price:"$"},
    {name:"Filet & Vine",coords:[32.3775,-86.2555],cuisine:"Steakhouse",rating:4.2,price:"$$$"},
    {name:"Taste of Bangkok",coords:[32.4040,-86.2715],cuisine:"Thai",rating:4.1,price:"$$"},
    {name:"Maki Fresh",coords:[32.3780,-86.2550],cuisine:"Sushi & Poke",rating:4.0,price:"$$"},
    {name:"The Greenhouse",coords:[32.3565,-86.3245],cuisine:"Coffee & Pastries",rating:4.4,price:"$"},
    {name:"Martin's Restaurant",coords:[32.3695,-86.2885],cuisine:"Southern Soul Food",rating:4.2,price:"$"}
  ]
};
